[package]
name = "shards-tech/journal"
description = "Logging makes easy and efficient! https://github.com/shards-tech/journal.git"
authors = ["Bloomy <dequeyuri@gmail.com>"]

version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["init.lua", "wally.toml"]

[dependencies]